var products = [
  {
    "id": 1,
    "title": "Biryani",
    "description": "A flavorful and aromatic rice dish with spices and meat.",
    "price": 250,
    "image":
        "https://media.istockphoto.com/id/1058029096/photo/chicken-biryani.jpg?s=612x612&w=0&k=20&c=yVV1RArkYz1fXf0Blpeuwxt0yTHHDnlOURVMJmYgAeI=",
    "category": "Main Course",
    "isVeg": false,
  },
  {
    "id": 2,
    "title": "Paneer Tikka",
    "description":
        "Marinated and grilled paneer cubes served with mint chutney.",
    "price": 180,
    "image":
        "https://media.istockphoto.com/id/1186759773/photo/paneer-tikka-at-skewers-in-black-bowl-at-dark-slate-background-paneer-tikka-is-an-indian.jpg?s=612x612&w=0&k=20&c=LYsyEmVzFMff1U7XQw_QmarM7G2KFudCwmR7TsYVSRM=",
    "category": "Appetizer",
    "isVeg": true,
  },
  {
    "id": 3,
    "title": "Masala Dosa",
    "description": "Crispy rice crepe filled with spiced mashed potatoes.",
    "price": 120,
    "image":
        "https://media.istockphoto.com/id/1303091718/photo/kerala-vegetarian-foods-dosa-with-curries.jpg?s=612x612&w=0&k=20&c=fMaq0nQaMUjKYe6XkMLJYUCshkMF5jdPBU-O0RYT3X0=",
    "category": "Breakfast",
    "isVeg": true,
  },
  {
    "id": 4,
    "title": "Butter Chicken",
    "description": "Creamy and rich chicken curry with a buttery tomato sauce.",
    "price": 280,
    "image": "https://media.istockphoto.com/id/1472620857/photo/tasty-butter-chicken-curry-dish-from-indian-cuisine.jpg?s=612x612&w=0&k=20&c=7Lf1Qrwj7sY31LuzbO9u8KMFuoUo96SwOvxz5YL_Slw=",
    "category": "Main Course",
    "isVeg": false,
  },
  {
    "id": 5,
    "title": "Samosa",
    "description": "Crispy pastry filled with spiced potatoes and peas.",
    "price": 60,
    "image": "https://media.istockphoto.com/id/1167500959/photo/delicious-vegan-samosa-with-hot-tea.jpg?s=612x612&w=0&k=20&c=O5Aeopf7trMcA2trwfc4h5wNQPinB9xJZDWUB_pBOdQ=",
    "category": "Snack",
    "isVeg": true,
  },
  {
    "id": 6,
    "title": "Rajma Chawal",
    "description": "Kidney beans curry served with rice.",
    "price": 150,
    "image": "https://media.istockphoto.com/id/669635320/photo/kidney-bean-curry-or-rajma-or-rajmah-chawal-and-roti-typical-north-indian-main-course.jpg?s=612x612&w=0&k=20&c=3ir3vZKHa2oPXkpEKHLbWPAPF1yhxRCyr4DIew41pzg=",
    "category": "Main Course",
    "isVeg": true,
  },
  {
    "id": 7,
    "title": "Chicken Biryani",
    "description": "Spiced rice dish with flavorful chicken pieces.",
    "price": 300,
    "image": "https://media.istockphoto.com/id/1345624336/photo/chicken-biriyani.jpg?s=612x612&w=0&k=20&c=adU_N0P-1SKMQLZu5yu7aPknfLLgbViI8XILqLP92A4=",
    "category": "Main Course",
    "isVeg": false,
  },
  {
    "id": 8,
    "title": "Aloo Paratha",
    "description": "Stuffed flatbread with spiced mashed potatoes.",
    "price": 90,
    "image": "https://media.istockphoto.com/id/1197783347/photo/aalo-paratha-in-rusty-background.jpg?s=2048x2048&w=is&k=20&c=OTd-CrtqAXefTbsXHKVHMKo3ad3ASJmhEQZXlo7bWvM=",
    "category": "Breakfast",
    "isVeg": true,
  },
  {
    "id": 9,
    "title": "Fish Curry",
    "description": "Fish curry with coconut milk and aromatic spices.",
    "price": 260,
    "image": "https://media.istockphoto.com/id/1295772368/photo/macher-jhol-in-black-bowl-on-dark-slate-table-top-indian-cuisine-bengali-fish-curry-asian.jpg?s=2048x2048&w=is&k=20&c=riBBJqeCNGKzQkG-Rrum3P2sHrh2vPn_BCVloqE_A3k=",
    "category": "Main Course",
    "isVeg": false,
  },
  {
    "id": 10,
    "title": "Chole Bhature",
    "description": "Chickpea curry served with deep-fried bread.",
    "price": 180,
    "image": "https://media.istockphoto.com/id/1328524212/photo/katlambe-chole.jpg?s=612x612&w=0&k=20&c=WImf2WcS08blqcijhLW6NS5baQ6-hVWgDxEhcgc62b4=",
    "category": "Main Course",
    "isVeg": true,
  },
];
